build-rest:
   stage: build
   script:
      - make trackEx
   artifacts:
      paths:
         - trackEx

build-test:
   stage: build
   script:
      - make testTrackEx
   artifacts:
      paths:
         - testTrackEx

test-rest:
   stage: test
   script:
      - testTrackEx
      - make memcheck-test
      - make static
      - make style

pages:
   stage: deploy
   dependencies:
      - test-rest
   script:
      - make coverage
      - make docs
   artifacts:
      paths:
         - coverage
         - docs
      expire_in: 14 days
   only:
      - master
      - dev
